// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6P5C2yIHnoRfolHcq-TRbWId9t4f-6CQ',
    appId: '1:553240619445:web:bbcb91c015ae963cd411fc',
    messagingSenderId: '553240619445',
    projectId: 'arcanabell-6c682',
    authDomain: 'arcanabell-6c682.firebaseapp.com',
    databaseURL: 'https://arcanabell-6c682-default-rtdb.firebaseio.com',
    storageBucket: 'arcanabell-6c682.appspot.com',
    measurementId: 'G-CX0FMCKB46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYfYIjQvMRqrQvcPPlty_5fzu7tpL5W24',
    appId: '1:553240619445:android:19761299cdf5b1c4d411fc',
    messagingSenderId: '553240619445',
    projectId: 'arcanabell-6c682',
    databaseURL: 'https://arcanabell-6c682-default-rtdb.firebaseio.com',
    storageBucket: 'arcanabell-6c682.appspot.com',
  );
}
